[package]
name = "oxi-pdf"
version = "0.1.0"
authors = ["Agi Sferro <agi@sferro.dev>"]
edition = "2018"

[dependencies]
deflate = { path = "../deflate" }
uuid = { version = "0.7", features = ["v4"] }
