[package]
name = "deflate"
version = "0.1.0"
authors = ["Agi Sferro <agi@sferro.dev>"]
edition = "2018"

[lib]
name = "deflate"
path = "src/lib.rs"

[[bin]]
name = "deflate-cmd"
path = "src/cmd.rs"

[dependencies]
clap = "2.32.0"
